// ============================================================
// GENERATED FROM docs/form.xlsx — DO NOT EDIT BY HAND.
// Run `npm run generate:schema` to regenerate.
// ============================================================

import type { Question } from "./schema-types";

type Answers = Record<string, unknown>;

export const questions: Question[] = [
  {
    id: "consent",
    kind: "note",
    prompt: "This research is being conducted as part of a PhD within the School of Geography and Environmental Sciences at the University of Ulster. The study aims to examine public views and experiences relating to wildlife in Ireland to inform wildlife management.",
    required: false,
  },
  {
    id: "species_f",
    kind: "single",
    prompt: "Please identify the animal in the photo above from the options below?",
    required: true,
    choices: [{"value":"pine_marten","label":"Pine marten"},{"value":"fox","label":"Fox"},{"value":"stoat","label":"Stoat"},{"value":"ferret","label":"Ferret"},{"value":"domestic_cat","label":"Domestic cat"},{"value":"badger","label":"Badger"},{"value":"not_sure","label":"Not sure / I don’t know"}],
    layout: "horizontal",
  },
  {
    id: "confidence_f",
    kind: "slider",
    prompt: "How confident are you that you could recognise this animal if you saw it in person?",
    required: true,
    leftLabel: "Not at all confident",
    rightLabel: "Very confident",
    anchors: [],
  },
  {
    id: "species_pm",
    kind: "single",
    prompt: "Please identify the animal in the photo above from the options below?",
    required: true,
    choices: [{"value":"pine_marten","label":"Pine marten"},{"value":"fox","label":"Fox"},{"value":"stoat","label":"Stoat"},{"value":"ferret","label":"Ferret"},{"value":"domestic_cat","label":"Domestic cat"},{"value":"badger","label":"Badger"},{"value":"not_sure","label":"Not sure / I don’t know"}],
    layout: "horizontal",
  },

  {
  id: "confidence_pm",
  kind: "slider-group",
  prompt: "How confident are you that you could recognise this animal if you saw it in person?",
  required: true,
  leftLabel: "Not at all confident",
  rightLabel: "Very confident",
  anchors: [
  "Not at all confident",
  "Slightly confident",
  "Moderately confident",
  "Confident",
  "Very confident",  ],
  items: [    {id: "confidence_pm", label: ""    }],
},
``
  {
    id: "seen_pm_matrix",
    kind: "choice-matrix",
    prompt: "Have you ever seen or noticed signs of this animal before? ",
    hint: "(For example, seeing or hearing one, or indirect signs such as tracks or droppings)",
    required: true,
    items: [{"id":"seen_pm","label":"Pine Marten"},{"id":"seen_fox","label":"Fox"}],
    choices: [{"value":"yes","label":"Yes"},{"value":"no","label":"No"},{"value":"unsure","label":"I’m not sure"}],
  },
  {
    id: "pm_scenarios",
    kind: "slider-group",
    prompt: "The following are hypothetical situations. For each one, please indicate how acceptable you think it is for a pine marten to behave in this way. ",
    required: true,
    leftLabel: "Completely unacceptable",
    rightLabel: "Completely acceptable",
    anchors: ["Completely unacceptable","Somewhat unacceptable","Neutral","Somewhat acceptable","Completely acceptable"],
    items: [{"id":"pm_a","label":"A. Pine marten is seen in its natural habitat (i.e. woodland)"},
      {"id":"pm_b","label":"B. Pine marten is seen around homes or farms (i.e, gardens, yards, farmyards)"},
      {"id":"pm_c","label":"C. Pine marten has denned in a house"},{"id":"pm_d","label":"D. Pine marten has attacked poultry and gamebirds"},
      {"id":"pm_e","label":"E. Pine marten has been seen eating from a bin"}],
  },
  {
    id: "fox_scenarios",
    kind: "slider-group",
    prompt: "The following are hypothetical situations. For each one, please indicate how acceptable you think it is for a fox to behave in this way. ",
    required: true,
    leftLabel: "Completely unacceptable",
    rightLabel: "Completely acceptable",
    anchors: ["Completely unacceptable","Somewhat unacceptable","Neutral","Somewhat acceptable","Completely acceptable"],
    items: [{"id":"fox_a","label":"A. Fox is seen in its natural habitat (i.e. woodland)"},{"id":"fox_b","label":"B. Fox is seen around homes or farms (i.e, gardens, yards, farmyards)"},{"id":"fox_c","label":"C. Fox has denned in a house"},{"id":"fox_d","label":"D. Fox has attacked poultry and gamebirds"},{"id":"fox_e","label":"E. Fox has been seen eating from a bin"}],
  },
  {
    id: "pm_risk",
    kind: "slider-group",
    prompt: "How much risk do you believe pine martens pose in the following contexts? ",
    required: true,
    leftLabel: "Very low risk - No noticeable impact or very rare incidents",
    rightLabel: "Very high risk - Severe, ongoing, or widespread problems",
    anchors: ["Very low risk - No noticeable impact or very rare incidents","Low risk - Occasional or minor issues","Moderate risk - Some localised problems or occasional losses","High risk - Frequent problems or clear evidence of damage/losses","Very high risk - Severe, ongoing, or widespread problems"],
    items: [{"id":"pm_pet","label":"Pine marten: Risk to pets (e.g., dogs, cats, rabbits)"},{"id":"pm_poultry","label":"Pine marten: Risk to poultry/gamebirds (e.g., chickens, pheasants)"},{"id":"pm_livestock","label":"Pine marten: Risk to livestock excluding poultry (e.g., sheep, goats, pigs)"},{"id":"pm_protected","label":"Pine marten: Risk to protected species (e.g., red squirrels, native ground-nesting birds)"},{"id":"pm_humans","label":"Pine marten: Risk of injury to people"}],
  },
  {
    id: "fox_risk",
    kind: "slider-group",
    prompt: "How much risk do you believe foxes pose in the following contexts? ",
    required: true,
    leftLabel: "Very low risk - No noticeable impact or very rare incidents",
    rightLabel: "Very high risk - Severe, ongoing, or widespread problems",
    anchors: ["Very low risk - No noticeable impact or very rare incidents","Low risk - Occasional or minor issues","Moderate risk - Some localised problems or occasional losses","High risk - Frequent problems or clear evidence of damage/losses","Very high risk - Severe, ongoing, or widespread problems"],
    items: [{"id":"fox_pet","label":"Fox: Risk to pets (e.g., dogs, cats, rabbits)"},{"id":"fox_poultry","label":"Fox: Risk to poultry/gamebirds (e.g., chickens, pheasants)"},{"id":"fox_livestock","label":"Fox: Risk to livestock excluding poultry (e.g., sheep, goats, pigs)"},{"id":"fox_protected","label":"Fox: Risk to protected species (e.g., red squirrels, native ground-nesting birds)"},{"id":"fox_humans","label":"Fox: Risk of injury to people"}],
  },
  {
    id: "pm_tolerance",
    kind: "slider-group",
    prompt: "Please indicate the extent to which you agree or disagree with the following statements regarding pine martens. ",
    required: true,
    leftLabel: "Strongly disagree",
    rightLabel: "Strongly agree",
    anchors: ["Strongly disagree","Disagree","Neutral","Agree","Strongly agree"],
    items: [{"id":"pm_benefits","label":"Pine martens provide ecological benefits that make their presence worthwhile (for example, controlling pests such as rodents or helping seed dispersal)"},{"id":"pm_tolerate","label":"I am willing to tolerate some inconvenience to allow pine martens to live in my local area (for example, accepting minor garden damage )"},{"id":"pm_prevent","label":"I would take steps to make interactions with pine martens less likely (for example, securing bins or installing electric fences to protect poultry)"},{"id":"pm_nonlethal","label":"Non-lethal measures should be used to manage pine martens (for example, deterrents  or artificial den boxes)"},{"id":"pm_lethal","label":"Lethal control should be permitted if pine martens cause significant or persistent damage or losses"}],
  },
  {
    id: "fox_tolerance",
    kind: "slider-group",
    prompt: "Please indicate the extent to which you agree or disagree with the following statements regarding foxes. ",
    required: true,
    leftLabel: "Strongly disagree",
    rightLabel: "Strongly agree",
    anchors: ["Strongly disagree","Disagree","Neutral","Agree","Strongly agree"],
    items: [{"id":"fox_benefits","label":"Foxes provide ecological benefits that make their presence worthwhile (for example, controlling pests such as rodents or helping seed dispersal)"},{"id":"fox_tolerate","label":"I am willing to tolerate some inconvenience to allow foxes to live in my local area (for example, accepting minor garden damage)"},{"id":"fox_prevent","label":"I would take steps to make interactions with foxes less likely (for example, installing electric fencing, or securing bins)"},{"id":"fox_nonlethal","label":"Non-lethal measures should be used to manage fox (for example, deterrents or artificial den boxes)"},{"id":"fox_lethal","label":"Lethal control should be permitted if foxes cause significant or persistent damage or losses"}],
  },
  {
    id: "sp_local_matrix",
    kind: "choice-matrix",
    prompt: "Which of the following experiences have you had with these animals?",
    required: true,
    items: [{"id":"sp_local","label":"Seen in my local area (e.g. nearby roads, woodland, fields)."},{"id":"sp_property","label":"Seen in my garden or on my property."},{"id":"sp_denning","label":"Experienced an animal denning (living or sleeping) in my home or outbuildings."},{"id":"sp_bins","label":"Experience an animal accessing  bins"},{"id":"sp_damage","label":"Experienced damage to my property."},{"id":"sp_losses","label":"Experienced loss of poultry, livestock, gamebirds, or pets."}],
    choices: [{"value":"fox","label":"Red fox"},{"value":"pm","label":"European pine marten"},{"value":"both","label":"Both"},{"value":"neither","label":"Neither"}],
  },
  {
    id: "other_interactions",
    kind: "text",
    prompt: "If you have experienced  any other interactions with these animals please leave details below",
    required: false,
    multiline: true,
  },
  {
    id: "sp_local_exp_pm",
    kind: "single",
    prompt: "Seen a pine marten my local area (e.g. nearby roads, woodland, fields).",
    required: true,
    choices: [{"value":"comp_neg","label":"Completely negative"},{"value":"som_neg","label":"Somewhat negative"},{"value":"neutral","label":"Neutral"},{"value":"som_pos","label":"Somewhat positive"},{"value":"comp_pos","label":"Completely positive"}],
    layout: "vertical",
    visibleIf: (answers: Answers) => (answers["sp_local"] === 'pm' || answers["sp_local"] === 'fox' || answers["sp_local"] === 'both' || answers["sp_property"] === 'pm' || answers["sp_property"] === 'fox' || answers["sp_property"] === 'both' || answers["sp_denning"] === 'pm' || answers["sp_denning"] === 'fox' || answers["sp_denning"] === 'both' || answers["sp_bins"] === 'pm' || answers["sp_bins"] === 'fox' || answers["sp_bins"] === 'both' || answers["sp_damage"] === 'pm' || answers["sp_damage"] === 'fox' || answers["sp_damage"] === 'both' || answers["sp_losses"] === 'pm' || answers["sp_losses"] === 'fox' || answers["sp_losses"] === 'both') && (answers["sp_local"] === 'pm' || answers["sp_local"] === 'both'),
  },
  {
    id: "sp_property_exp_pm",
    kind: "single",
    prompt: "Seen a pine marten in my garden or on my property.",
    required: true,
    choices: [{"value":"comp_neg","label":"Completely negative"},{"value":"som_neg","label":"Somewhat negative"},{"value":"neutral","label":"Neutral"},{"value":"som_pos","label":"Somewhat positive"},{"value":"comp_pos","label":"Completely positive"}],
    layout: "vertical",
    visibleIf: (answers: Answers) => (answers["sp_local"] === 'pm' || answers["sp_local"] === 'fox' || answers["sp_local"] === 'both' || answers["sp_property"] === 'pm' || answers["sp_property"] === 'fox' || answers["sp_property"] === 'both' || answers["sp_denning"] === 'pm' || answers["sp_denning"] === 'fox' || answers["sp_denning"] === 'both' || answers["sp_bins"] === 'pm' || answers["sp_bins"] === 'fox' || answers["sp_bins"] === 'both' || answers["sp_damage"] === 'pm' || answers["sp_damage"] === 'fox' || answers["sp_damage"] === 'both' || answers["sp_losses"] === 'pm' || answers["sp_losses"] === 'fox' || answers["sp_losses"] === 'both') && (answers["sp_property"] === 'pm' || answers["sp_property"] === 'both'),
  },
  {
    id: "sp_denning_exp_pm",
    kind: "single",
    prompt: "Experienced a pine marten denning (living or sleeping) in my home or outbuildings.",
    required: true,
    choices: [{"value":"comp_neg","label":"Completely negative"},{"value":"som_neg","label":"Somewhat negative"},{"value":"neutral","label":"Neutral"},{"value":"som_pos","label":"Somewhat positive"},{"value":"comp_pos","label":"Completely positive"}],
    layout: "vertical",
    visibleIf: (answers: Answers) => (answers["sp_local"] === 'pm' || answers["sp_local"] === 'fox' || answers["sp_local"] === 'both' || answers["sp_property"] === 'pm' || answers["sp_property"] === 'fox' || answers["sp_property"] === 'both' || answers["sp_denning"] === 'pm' || answers["sp_denning"] === 'fox' || answers["sp_denning"] === 'both' || answers["sp_bins"] === 'pm' || answers["sp_bins"] === 'fox' || answers["sp_bins"] === 'both' || answers["sp_damage"] === 'pm' || answers["sp_damage"] === 'fox' || answers["sp_damage"] === 'both' || answers["sp_losses"] === 'pm' || answers["sp_losses"] === 'fox' || answers["sp_losses"] === 'both') && (answers["sp_denning"] === 'pm' || answers["sp_denning"] === 'both'),
  },
  {
    id: "sp_bins_exp_pm",
    kind: "single",
    prompt: "Experience a pine marten accessing  bins",
    required: true,
    choices: [{"value":"comp_neg","label":"Completely negative"},{"value":"som_neg","label":"Somewhat negative"},{"value":"neutral","label":"Neutral"},{"value":"som_pos","label":"Somewhat positive"},{"value":"comp_pos","label":"Completely positive"}],
    layout: "vertical",
    visibleIf: (answers: Answers) => (answers["sp_local"] === 'pm' || answers["sp_local"] === 'fox' || answers["sp_local"] === 'both' || answers["sp_property"] === 'pm' || answers["sp_property"] === 'fox' || answers["sp_property"] === 'both' || answers["sp_denning"] === 'pm' || answers["sp_denning"] === 'fox' || answers["sp_denning"] === 'both' || answers["sp_bins"] === 'pm' || answers["sp_bins"] === 'fox' || answers["sp_bins"] === 'both' || answers["sp_damage"] === 'pm' || answers["sp_damage"] === 'fox' || answers["sp_damage"] === 'both' || answers["sp_losses"] === 'pm' || answers["sp_losses"] === 'fox' || answers["sp_losses"] === 'both') && (answers["sp_bins"] === 'pm' || answers["sp_bins"] === 'both'),
  },
  {
    id: "sp_damage_exp_pm",
    kind: "single",
    prompt: "Experienced damage to my property by a pine marten.",
    required: true,
    choices: [{"value":"comp_neg","label":"Completely negative"},{"value":"som_neg","label":"Somewhat negative"},{"value":"neutral","label":"Neutral"},{"value":"som_pos","label":"Somewhat positive"},{"value":"comp_pos","label":"Completely positive"}],
    layout: "vertical",
    visibleIf: (answers: Answers) => (answers["sp_local"] === 'pm' || answers["sp_local"] === 'fox' || answers["sp_local"] === 'both' || answers["sp_property"] === 'pm' || answers["sp_property"] === 'fox' || answers["sp_property"] === 'both' || answers["sp_denning"] === 'pm' || answers["sp_denning"] === 'fox' || answers["sp_denning"] === 'both' || answers["sp_bins"] === 'pm' || answers["sp_bins"] === 'fox' || answers["sp_bins"] === 'both' || answers["sp_damage"] === 'pm' || answers["sp_damage"] === 'fox' || answers["sp_damage"] === 'both' || answers["sp_losses"] === 'pm' || answers["sp_losses"] === 'fox' || answers["sp_losses"] === 'both') && (answers["sp_damage"] === 'pm' || answers["sp_damage"] === 'both'),
  },
  {
    id: "sp_losses_exp_pm",
    kind: "single",
    prompt: "Experienced loss of poultry, livestock, gamebirds, or pets due to a pine marten. ",
    required: true,
    choices: [{"value":"comp_neg","label":"Completely negative"},{"value":"som_neg","label":"Somewhat negative"},{"value":"neutral","label":"Neutral"},{"value":"som_pos","label":"Somewhat positive"},{"value":"comp_pos","label":"Completely positive"}],
    layout: "vertical",
    visibleIf: (answers: Answers) => (answers["sp_local"] === 'pm' || answers["sp_local"] === 'fox' || answers["sp_local"] === 'both' || answers["sp_property"] === 'pm' || answers["sp_property"] === 'fox' || answers["sp_property"] === 'both' || answers["sp_denning"] === 'pm' || answers["sp_denning"] === 'fox' || answers["sp_denning"] === 'both' || answers["sp_bins"] === 'pm' || answers["sp_bins"] === 'fox' || answers["sp_bins"] === 'both' || answers["sp_damage"] === 'pm' || answers["sp_damage"] === 'fox' || answers["sp_damage"] === 'both' || answers["sp_losses"] === 'pm' || answers["sp_losses"] === 'fox' || answers["sp_losses"] === 'both') && (answers["sp_losses"] === 'pm' || answers["sp_losses"] === 'both'),
  },
  {
    id: "sp_local_exp_fox",
    kind: "single",
    prompt: "Seen a fox my local area (e.g. nearby roads, woodland, fields).",
    required: true,
    choices: [{"value":"comp_neg","label":"Completely negative"},{"value":"som_neg","label":"Somewhat negative"},{"value":"neutral","label":"Neutral"},{"value":"som_pos","label":"Somewhat positive"},{"value":"comp_pos","label":"Completely positive"}],
    layout: "vertical",
    visibleIf: (answers: Answers) => (answers["sp_local"] === 'pm' || answers["sp_local"] === 'fox' || answers["sp_local"] === 'both' || answers["sp_property"] === 'pm' || answers["sp_property"] === 'fox' || answers["sp_property"] === 'both' || answers["sp_denning"] === 'pm' || answers["sp_denning"] === 'fox' || answers["sp_denning"] === 'both' || answers["sp_bins"] === 'pm' || answers["sp_bins"] === 'fox' || answers["sp_bins"] === 'both' || answers["sp_damage"] === 'pm' || answers["sp_damage"] === 'fox' || answers["sp_damage"] === 'both' || answers["sp_losses"] === 'pm' || answers["sp_losses"] === 'fox' || answers["sp_losses"] === 'both') && (answers["sp_local"] === 'fox' || answers["sp_local"] === 'both'),
  },
  {
    id: "sp_property_exp_fox",
    kind: "single",
    prompt: "Seen a fox in my garden or on my property.",
    required: true,
    choices: [{"value":"comp_neg","label":"Completely negative"},{"value":"som_neg","label":"Somewhat negative"},{"value":"neutral","label":"Neutral"},{"value":"som_pos","label":"Somewhat positive"},{"value":"comp_pos","label":"Completely positive"}],
    layout: "vertical",
    visibleIf: (answers: Answers) => (answers["sp_local"] === 'pm' || answers["sp_local"] === 'fox' || answers["sp_local"] === 'both' || answers["sp_property"] === 'pm' || answers["sp_property"] === 'fox' || answers["sp_property"] === 'both' || answers["sp_denning"] === 'pm' || answers["sp_denning"] === 'fox' || answers["sp_denning"] === 'both' || answers["sp_bins"] === 'pm' || answers["sp_bins"] === 'fox' || answers["sp_bins"] === 'both' || answers["sp_damage"] === 'pm' || answers["sp_damage"] === 'fox' || answers["sp_damage"] === 'both' || answers["sp_losses"] === 'pm' || answers["sp_losses"] === 'fox' || answers["sp_losses"] === 'both') && (answers["sp_property"] === 'fox' || answers["sp_property"] === 'both'),
  },
  {
    id: "sp_denning_exp_fox",
    kind: "single",
    prompt: "Experienced a fox denning (living or sleeping) in my home or outbuildings.",
    required: true,
    choices: [{"value":"comp_neg","label":"Completely negative"},{"value":"som_neg","label":"Somewhat negative"},{"value":"neutral","label":"Neutral"},{"value":"som_pos","label":"Somewhat positive"},{"value":"comp_pos","label":"Completely positive"}],
    layout: "vertical",
    visibleIf: (answers: Answers) => (answers["sp_local"] === 'pm' || answers["sp_local"] === 'fox' || answers["sp_local"] === 'both' || answers["sp_property"] === 'pm' || answers["sp_property"] === 'fox' || answers["sp_property"] === 'both' || answers["sp_denning"] === 'pm' || answers["sp_denning"] === 'fox' || answers["sp_denning"] === 'both' || answers["sp_bins"] === 'pm' || answers["sp_bins"] === 'fox' || answers["sp_bins"] === 'both' || answers["sp_damage"] === 'pm' || answers["sp_damage"] === 'fox' || answers["sp_damage"] === 'both' || answers["sp_losses"] === 'pm' || answers["sp_losses"] === 'fox' || answers["sp_losses"] === 'both') && (answers["sp_denning"] === 'fox' || answers["sp_denning"] === 'both'),
  },
  {
    id: "sp_bins_exp_fox",
    kind: "single",
    prompt: "Experience a fox accessing  bins.",
    required: true,
    choices: [{"value":"comp_neg","label":"Completely negative"},{"value":"som_neg","label":"Somewhat negative"},{"value":"neutral","label":"Neutral"},{"value":"som_pos","label":"Somewhat positive"},{"value":"comp_pos","label":"Completely positive"}],
    layout: "vertical",
    visibleIf: (answers: Answers) => (answers["sp_local"] === 'pm' || answers["sp_local"] === 'fox' || answers["sp_local"] === 'both' || answers["sp_property"] === 'pm' || answers["sp_property"] === 'fox' || answers["sp_property"] === 'both' || answers["sp_denning"] === 'pm' || answers["sp_denning"] === 'fox' || answers["sp_denning"] === 'both' || answers["sp_bins"] === 'pm' || answers["sp_bins"] === 'fox' || answers["sp_bins"] === 'both' || answers["sp_damage"] === 'pm' || answers["sp_damage"] === 'fox' || answers["sp_damage"] === 'both' || answers["sp_losses"] === 'pm' || answers["sp_losses"] === 'fox' || answers["sp_losses"] === 'both') && (answers["sp_bins"] === 'fox' || answers["sp_bins"] === 'both'),
  },
  {
    id: "sp_damage_exp_fox",
    kind: "single",
    prompt: "Experienced damage to my property by a fox.",
    required: true,
    choices: [{"value":"comp_neg","label":"Completely negative"},{"value":"som_neg","label":"Somewhat negative"},{"value":"neutral","label":"Neutral"},{"value":"som_pos","label":"Somewhat positive"},{"value":"comp_pos","label":"Completely positive"}],
    layout: "vertical",
    visibleIf: (answers: Answers) => (answers["sp_local"] === 'pm' || answers["sp_local"] === 'fox' || answers["sp_local"] === 'both' || answers["sp_property"] === 'pm' || answers["sp_property"] === 'fox' || answers["sp_property"] === 'both' || answers["sp_denning"] === 'pm' || answers["sp_denning"] === 'fox' || answers["sp_denning"] === 'both' || answers["sp_bins"] === 'pm' || answers["sp_bins"] === 'fox' || answers["sp_bins"] === 'both' || answers["sp_damage"] === 'pm' || answers["sp_damage"] === 'fox' || answers["sp_damage"] === 'both' || answers["sp_losses"] === 'pm' || answers["sp_losses"] === 'fox' || answers["sp_losses"] === 'both') && (answers["sp_damage"] === 'fox' || answers["sp_damage"] === 'both'),
  },
  {
    id: "sp_losses_exp_fox",
    kind: "single",
    prompt: "Experienced loss of poultry, livestock, gamebirds, or pets due to a fox. ",
    required: true,
    choices: [{"value":"comp_neg","label":"Completely negative"},{"value":"som_neg","label":"Somewhat negative"},{"value":"neutral","label":"Neutral"},{"value":"som_pos","label":"Somewhat positive"},{"value":"comp_pos","label":"Completely positive"}],
    layout: "vertical",
    visibleIf: (answers: Answers) => (answers["sp_local"] === 'pm' || answers["sp_local"] === 'fox' || answers["sp_local"] === 'both' || answers["sp_property"] === 'pm' || answers["sp_property"] === 'fox' || answers["sp_property"] === 'both' || answers["sp_denning"] === 'pm' || answers["sp_denning"] === 'fox' || answers["sp_denning"] === 'both' || answers["sp_bins"] === 'pm' || answers["sp_bins"] === 'fox' || answers["sp_bins"] === 'both' || answers["sp_damage"] === 'pm' || answers["sp_damage"] === 'fox' || answers["sp_damage"] === 'both' || answers["sp_losses"] === 'pm' || answers["sp_losses"] === 'fox' || answers["sp_losses"] === 'both') && (answers["sp_losses"] === 'fox' || answers["sp_losses"] === 'both'),
  },
  {
    id: "season",
    kind: "multi",
    prompt: "If you can remember, please tell us what time of the year (s) these experiences happened.",
    hint: "[object Object]",
    required: false,
    choices: [{"value":"spring","label":"Spring (March–May)"},{"value":"summer","label":"Summer (June–August)"},{"value":"autumn","label":"Autumn (September–November)"},{"value":"winter","label":"Winter (December–February)"},{"value":"unsure","label":"Not sure"}],
    visibleIf: (answers: Answers) => answers["sp_losses"] === 'fox' || answers["sp_losses"] === 'pm' || answers["sp_losses"] === 'both',
  },
  {
    id: "loss_details",
    kind: "text",
    prompt: "Where you have suffered animal losses, please provide details where you feel comfortable, including the type of animals lost and the number for each occasion, where possible.",
    required: false,
    multiline: true,
    visibleIf: (answers: Answers) => answers["sp_losses"] === 'fox' || answers["sp_losses"] === 'pm' || answers["sp_losses"] === 'both',
  },
  {
    id: "signs_losses",
    kind: "text",
    prompt: "Where there any signs that told you this animal caused the loss?",
    hint: "(Please describe anything that helped you identify the animal. For example: tracks, droppings, bite marks, or seeing the animal)",
    required: false,
    multiline: true,
    visibleIf: (answers: Answers) => answers["sp_losses"] === 'fox' || answers["sp_losses"] === 'pm' || answers["sp_losses"] === 'both',
  },
  {
    id: "other_sp_interactions",
    kind: "text",
    prompt: "If you have any other interactions with animals on the island of Ireland you would like to share, please do so here (this may be other species not mentioned in this survey). ",
    required: false,
    multiline: true,
  },
  {
    id: "age",
    kind: "single",
    prompt: "How old are you?",
    required: true,
    choices: [{"value":"a18_24","label":"18–24"},{"value":"a25_34","label":"25–34"},{"value":"a35_44","label":"35–44"},{"value":"a45_54","label":"45–54"},{"value":"a55_64","label":"55–64"},{"value":"a65p","label":"65+"},{"value":"pnts","label":"Prefer not to say"}],
    layout: "horizontal",
  },
  {
    id: "gender",
    kind: "single",
    prompt: "What is your gender?",
    required: true,
    choices: [{"value":"male","label":"Male"},{"value":"female","label":"Female"},{"value":"other","label":"Other"},{"value":"pnts","label":"Prefer not to say"}],
    layout: "horizontal",
  },
  {
    id: "postcode",
    kind: "text",
    prompt: "Please enter the Eircode or postcode of where you currently live. ",
    hint: "This helps us understand how views and experiences may vary across different parts of the island of Ireland. As stated at the beginning, your response will remain anonymous.",
    required: true,
    multiline: false,
    validate: "postcode-ie-ni",
  },
  {
    id: "job",
    kind: "single",
    prompt: "Which of the following best describes the industry you currently work in?",
    required: true,
    choices: [{"value":"agri","label":"Agriculture, Forestry & Fishing"},{"value":"manuf","label":"Manufacturing"},{"value":"constr","label":"Construction"},{"value":"retail","label":"Wholesale & Retail Trade"},{"value":"transp","label":"Transportation & Storage"},{"value":"info","label":"Information & Communication"},{"value":"finance","label":"Finance & Insurance"},{"value":"prof","label":"Professional, Scientific & Technical"},{"value":"educ","label":"Education"},{"value":"health","label":"Health & Social Work"},{"value":"public","label":"Public Administration"},{"value":"arts","label":"Arts, Entertainment & Recreation"},{"value":"accom","label":"Accommodation & Food Service"},{"value":"other","label":"Other"},{"value":"pnts","label":"Prefer not to say"}],
    layout: "horizontal",
  },
  {
    id: "hobbies",
    kind: "multi",
    prompt: "Which of the following areas do you have an interest in, either as a hobby, personal activity, or professional involvement? ",
    hint: "(Select all that apply)",
    required: false,
    choices: [{"value":"comm","label":"Community or group activities"},{"value":"soc","label":"Socialising with friends or family"},{"value":"arts","label":"Arts, culture or events"},{"value":"relax","label":"Relaxing or quiet time"},{"value":"sport","label":"Exercise or sport"},{"value":"outdoor","label":"Outdoor recreation"},{"value":"country","label":"Countryside pursuits"},{"value":"creative","label":"Creative hobbies"},{"value":"digital","label":"Digital entertainment"},{"value":"eatout","label":"Eating out"},{"value":"other","label":"Other"}],
  },
  {
    id: "comments",
    kind: "text",
    prompt: "If you have any additional comments, feedback or notes please leave them here.",
    required: false,
    multiline: true,
  }
];

export const questionsById: Record<string, Question> = Object.fromEntries(
  questions.map((q) => [q.id, q])
);

// XLSForm question names in original sheet order — used for the
// canonical Google Sheet header row.
export const sheetOrderedIds: string[] = [
  "consent",
  "species_f",
  "confidence_f",
  "species_pm",
  "confidence_pm",
  "seen_pm",
  "seen_fox",
  "pm_a",
  "pm_b",
  "pm_c",
  "pm_d",
  "pm_e",
  "fox_a",
  "fox_b",
  "fox_c",
  "fox_d",
  "fox_e",
  "pm_pet",
  "pm_poultry",
  "pm_livestock",
  "pm_protected",
  "pm_humans",
  "fox_pet",
  "fox_poultry",
  "fox_livestock",
  "fox_protected",
  "fox_humans",
  "pm_benefits",
  "pm_tolerate",
  "pm_prevent",
  "pm_nonlethal",
  "pm_lethal",
  "fox_benefits",
  "fox_tolerate",
  "fox_prevent",
  "fox_nonlethal",
  "fox_lethal",
  "sp_local",
  "sp_property",
  "sp_denning",
  "sp_bins",
  "sp_damage",
  "sp_losses",
  "other_interactions",
  "sp_local_exp_pm",
  "sp_property_exp_pm",
  "sp_denning_exp_pm",
  "sp_bins_exp_pm",
  "sp_damage_exp_pm",
  "sp_losses_exp_pm",
  "sp_local_exp_fox",
  "sp_property_exp_fox",
  "sp_denning_exp_fox",
  "sp_bins_exp_fox",
  "sp_damage_exp_fox",
  "sp_losses_exp_fox",
  "season",
  "loss_details",
  "signs_losses",
  "other_sp_interactions",
  "age",
  "gender",
  "postcode",
  "job",
  "hobbies",
  "comments"
];
